# Generated by Django 3.2.15 on 2023-12-08 06:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('message', '0003_auto_20231207_2041'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message',
            table='message',
        ),
    ]
