# Generated by Django 3.2.15 on 2023-12-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_alter_message_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_status',
            field=models.IntegerField(choices=[(1, '已读'), (0, '未读')], db_index=True, default=0),
        ),
    ]
