# Generated by Django 3.2.15 on 2023-12-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zone_id', models.AutoField(primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=255)),
                ('zone_description', models.TextField()),
                ('zone_image', models.ImageField(upload_to='zone_images/')),
                ('zone_status', models.IntegerField()),
            ],
            options={
                'verbose_name': '专区管理',
                'verbose_name_plural': '专区管理',
            },
        ),
    ]
