# Generated by Django 3.2.15 on 2023-12-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='zone_status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '异常')], default=1),
        ),
    ]
