# Generated by Django 3.2.15 on 2023-12-08 06:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('zone', '0002_alter_zone_zone_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='zone',
            table='zone',
        ),
    ]
