# Generated by Django 3.2.15 on 2023-12-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0004_zone_zone_layout_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='zone_layout_mode',
            field=models.IntegerField(choices=[(1, '普通'), (2, '融合'), (3, '普通排行'), (4, '融合排行'), (5, '普通沉浸排行')], default=1),
        ),
    ]
