# Generated by Django 3.2.15 on 2023-12-15 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0005_alter_zone_zone_layout_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='zone_create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
