# Generated by Django 3.2.15 on 2023-12-15 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0007_zone_zone_last_update_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zone',
            old_name='zone_last_update_time',
            new_name='zone_last_active_time',
        ),
    ]
