# Generated by Django 3.2.15 on 2023-12-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0008_rename_zone_last_update_time_zone_zone_last_active_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='zone_last_active_time',
            field=models.DateTimeField(),
        ),
    ]
