# Generated by Django 3.2.15 on 2023-12-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20231207_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.IntegerField(choices=[(1, '正常'), (2, '审核中'), (3, '审核不通过')], default=1),
        ),
    ]
