# Generated by Django 3.2.15 on 2023-12-07 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='post_update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
