# Generated by Django 3.2.15 on 2023-12-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20231207_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
