# Generated by Django 3.2.15 on 2023-12-08 06:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('post', '0005_auto_20231207_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_time',
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
