# Generated by Django 3.2.15 on 2023-12-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_recentbrowsing_recent_create_time'),
        ('collection', '0007_rename_collection_time_collection_collection_create_time'),
        ('post', '0006_auto_20231208_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_id',
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ManyToManyField(through='collection.Collection', to='user.User'),
        ),
    ]
