# Generated by Django 3.2.15 on 2023-12-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20231213_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='post/default.png', upload_to='post/%Y/%m'),
        ),
    ]
