# Generated by Django 3.2.15 on 2023-12-14 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_favorite',
        ),
    ]
