# Generated by Django 3.2.15 on 2023-12-14 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_remove_post_post_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_comment',
        ),
    ]
