# Generated by Django 3.2.15 on 2023-12-22 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_rename_recent_create_time_recentbrowsing_recent_browsing_time'),
        ('post', '0012_post_post_layout_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('post_like_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_like_time', models.DateTimeField(auto_now_add=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': '帖子点赞',
                'verbose_name_plural': '帖子点赞',
                'db_table': 'post_like',
            },
        ),
    ]
