# Generated by Django 3.2.15 on 2023-12-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_postlike_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.BinaryField(),
        ),
    ]
