# Generated by Django 3.2.15 on 2023-12-05 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collection_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_index=True)),
                ('collection_time', models.DateTimeField(auto_now_add=True)),
                ('collection_type', models.IntegerField()),
                ('collection_status', models.IntegerField()),
                ('collection_time_index', models.DateTimeField(db_index=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
            options={
                'verbose_name': '收藏管理',
                'verbose_name_plural': '收藏管理',
            },
        ),
    ]
