# Generated by Django 3.2.15 on 2023-12-07 11:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='collection_status',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='collection_type',
        ),
    ]
