# Generated by Django 3.2.15 on 2023-12-07 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
        ('collection', '0002_auto_20231207_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='collection',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
