# Generated by Django 3.2.15 on 2023-12-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('collection', '0003_auto_20231207_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '删除')], default=1),
        ),
    ]
