# Generated by Django 3.2.15 on 2023-12-08 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_alter_collection_collection_time_index'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='collection',
            table='collection',
        ),
    ]
