# Generated by Django 3.2.15 on 2023-12-13 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_alter_collection_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='collection_time',
            new_name='collection_create_time',
        ),
    ]
