# Generated by Django 3.2.15 on 2023-12-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_post_image'),
        ('user', '0014_alter_recentbrowsing_unique_together'),
        ('collection', '0007_rename_collection_time_collection_collection_create_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('user_id', 'post_id')},
        ),
    ]
