# Generated by Django 3.2.15 on 2023-12-22 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_alter_collection_collection_time_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='collection_status',
        ),
    ]
