# Generated by Django 3.2.15 on 2023-12-21 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0017_rename_recent_create_time_recentbrowsing_recent_browsing_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('help_id', models.AutoField(primary_key=True, serialize=False)),
                ('help_title', models.CharField(max_length=100)),
                ('help_content', models.TextField()),
                ('help_time', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': '帮助管理',
                'verbose_name_plural': '帮助管理',
                'db_table': 'help',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_content', models.TextField()),
                ('feedback_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('feedback_reply', models.TextField(blank=True, null=True)),
                ('feedback_rate', models.IntegerField(default=0)),
                ('feedback_status', models.IntegerField(choices=[(0, '已解决'), (1, '待解决')], default=1)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': '反馈管理',
                'verbose_name_plural': '反馈管理',
                'db_table': 'feedback',
            },
        ),
    ]
