# Generated by Django 3.2.15 on 2023-12-27 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0017_rename_recent_create_time_recentbrowsing_recent_browsing_time'),
        ('post', '0016_alter_post_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_content', models.TextField()),
                ('review_time', models.DateTimeField(auto_now_add=True)),
                ('review_status', models.IntegerField(choices=[(1, '正常'), (2, '审核中'), (3, '审核不通过')], default=1)),
                ('review_time_index', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='review.review')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': '评论管理',
                'verbose_name_plural': '评论管理',
                'db_table': 'review',
            },
        ),
    ]
