# Generated by Django 3.2.15 on 2023-12-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('content_id', models.IntegerField()),
                ('review_content', models.TextField()),
                ('review_time', models.DateTimeField(auto_now_add=True)),
                ('parent_id', models.IntegerField()),
                ('review_like', models.IntegerField(default=0)),
                ('review_type', models.IntegerField()),
                ('review_status', models.IntegerField()),
                ('review_time_index', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': '评论管理',
                'verbose_name_plural': '评论管理',
            },
        ),
    ]
