# Generated by Django 3.2.15 on 2023-12-07 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20231207_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='review.review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_status',
            field=models.IntegerField(choices=[(1, '正常'), (2, '审核中'), (3, '审核不通过')], default=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_type',
            field=models.IntegerField(choices=[(1, '评论帖子'), (2, '回复评论')]),
        ),
    ]
