# Generated by Django 3.2.15 on 2023-12-07 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20231207_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_type',
        ),
    ]
