# Generated by Django 3.2.15 on 2023-12-08 06:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('review', '0005_alter_review_review_time_index'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
    ]
