# Generated by Django 3.2.15 on 2023-12-16 09:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_alter_review_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_time_index',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 16, 9, 41, 5, 692005, tzinfo=utc)),
        ),
    ]
