# Generated by Django 3.2.15 on 2023-12-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_index=True, max_length=20, unique=True)),
                ('user_password', models.CharField(max_length=20)),
                ('user_email', models.CharField(db_index=True, max_length=30, unique=True)),
                ('user_phone', models.CharField(db_index=True, max_length=11, unique=True)),
                ('user_status', models.IntegerField(default=1)),
                ('user_create_time', models.DateTimeField(auto_now_add=True)),
                ('user_update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
            },
        ),
    ]
