# Generated by Django 3.2.15 on 2023-12-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='user_headicon',
            field=models.ImageField(default='user_headicon/default.png', upload_to='user_headicon'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_sex',
            field=models.IntegerField(choices=[(1, '男'), (2, '女'), (0, '保密')], default=0),
        ),
    ]
