# Generated by Django 3.2.15 on 2023-12-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0005_recentbrowsing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.CharField(max_length=128),
        ),
    ]
