# Generated by Django 3.2.15 on 2023-12-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_nickname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '禁用'), (2, '冻结')], default=1),
        ),
    ]
