# Generated by Django 3.2.15 on 2023-12-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_recentbrowsing_recent_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_qq',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='user_wechat',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
