# Generated by Django 3.2.15 on 2023-12-14 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_post_image'),
        ('user', '0012_alter_recentbrowsing_recent_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentbrowsing',
            name='recent_post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
    ]
