# Generated by Django 3.2.15 on 2023-12-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20231220_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_phone',
            field=models.CharField(db_index=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_qq',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_wechat',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
