# Generated by Django 3.2.15 on 2023-12-21 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20231220_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recentbrowsing',
            old_name='recent_create_time',
            new_name='recent_browsing_time',
        ),
    ]
