# Generated by Django 3.2.15 on 2024-01-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_rename_recent_create_time_recentbrowsing_recent_browsing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_sex',
            field=models.IntegerField(choices=[(1, '男'), (2, '女'), (0, '保密')], default=0),
        ),
    ]
