# Generated by Django 3.2.15 on 2024-01-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_user_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.IntegerField(choices=[(1, '正常'), (2, '冻结')], default=1),
        ),
    ]
